### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by jayantanth** [KaniyamFoundation/Indic_wikisource_stats#2]
Please have a look for https://shrinitools.toolforge.org/indic_ws_stats/ its shown 502 Bad Gateway

**Comment by tshrinivasan** [comment]
Will check tomorrow

**Comment by tshrinivasan** [comment]
Fixed the issue.

Discussed in #wikimedia-cloud irc channel.
They fixed the webserver issues and it works now.
